version: '3.8'

services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
  
  mysql-db:
      image: mysql/mysql-server:latest
      environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: users
        MYSQL_USER: root
        MYSQL_PASSWORD: rootpassword
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 3
      networks:
        - app-network

networks:
  app-network:
    driver: bridge