# Stage 1: Build the Go application
FROM golang:alpine AS build

WORKDIR /app



# Copy go.mod and go.sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container

COPY . .

# Build the Go application
RUN go build -o main .

# Stage 2: Create the final image
FROM alpine:latest

# Install necessary packages
RUN apk --no-cache add ca-certificates

# Set the working directory
WORKDIR /root/

COPY .env ./

# Copy the binary from the build stage
COPY --from=build /app/main .

# Make sure the binary is executable
RUN chmod +x ./main


# Expose the application port

EXPOSE 8080

# Command to run the application
CMD ["./main"]
